### ISSUE TITLE
Comment after the bundle keyword causes parsing error

### ISSUE THREAD

**Issue by larsewi** [miekg/cf#28]
You should be able to place comments anywhere, but a comment after the bundle keyword causes parsing error.
```
$ cat > test.cf
bundle # foo
agent test{}
$ cf-promises test.cf; echo $?  # Does cf-promises accept it? Exit 0 means yes.
0
$ cffmt test.cf 
2023/03/28 13:48:50 Failed to parse: parsing error
```

**Comment by miekg** [comment]
Is this really common? I ask, because cf-promise throws away comments when lexing, and cfcmt does not, so basically they can be put _anywhere_. I can add this spot to allow comments there, but I guess there will be multiple other places where you can still put them, and parsing will fail. i.e.
~~~ 
bundle agent #5 
test{}
~~~
will prolly also not parse.

**Comment by larsewi** [comment]
Indeed, which is why formatters are very hard to implement. No I do not think it's common to do that.

```
$ cffmt
bundle agent #5 
test{} 
2023/03/29 10:01:50 Failed to parse: parsing error
```

**Comment by miekg** [comment]
trying add some more comments spots (although unlikely to be used IRL)
But:
~~~
bundle #foo
agent test
{

}
~~~
has the lex tokens:
~~~
2023/06/02 12:35:23 chroma.Token {Keyword bundle}
2023/06/02 12:35:23 chroma.Token {Keyword #foo}
2023/06/02 12:35:23 chroma.Token {NameFunction agent}
2023/06/02 12:35:23 chroma.Token {NameFunction test}
2023/06/02 12:35:23 chroma.Token {Punctuation {}
2023/06/02 12:35:23 chroma.Token {Punctuation }}
~~~
So the lexer already doesn't handle this (`Keyword #foo`)

Same for my alternative:
~~~
2023/06/02 12:38:59 chroma.Token {NameFunction bundle}
2023/06/02 12:38:59 chroma.Token {NameFunction agent}
2023/06/02 12:38:59 chroma.Token {Comment #5
}
~~~
That 2nd line was `Keyword agent` so this is also not correctly lexed.

Closing this issue as it's not a matter of placing more `Comments(b)` lines in the parser, but goes deeper into the lexer *and* this is somewhat unlikely places to put comments.
